
module_name: "power-logging-module-24"
use_hw_timer: false # Disable hw timer based DMA update

buckets:
    current_channels:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 10
        parameters:
            # these must directly be a variable defined in GopherCAN
            vbatChan0Current_A:
                ADC: ADC3_IN0
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan1Current_A:
                ADC: ADC3_IN2
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan2Current_A:
                ADC: ADC3_IN3
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan3Current_A:
                ADC: ADC2_IN4
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan4Current_A:
                ADC: ADC2_IN5
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan5Current_A:
                ADC: ADC2_IN6
                sensor: vbat_channel_current
                samples_buffered: 10
            vbatChan6Current_A:
                ADC: ADC2_IN7
                sensor: vbat_channel_current
                samples_buffered: 10
            fiveVChan0Current_A:
                ADC: ADC2_IN8
                sensor: five_volt_channel_current
                samples_buffered: 10
            fiveVChan1Current_A:
                ADC: ADC3_IN10
                sensor: five_volt_channel_current
                samples_buffered: 10
            fiveVChan2Current_A:
                ADC: ADC3_IN11
                sensor: five_volt_channel_current
                samples_buffered: 10
            fiveVChan3Current_A:
                ADC: ADC3_IN12
                sensor: five_volt_channel_current
                samples_buffered: 10
            plmVbatVoltage_V:
                ADC: ADC2_IN13
                sensor: vbat_voltage_reading
                samples_buffered: 10
            plm5VVoltage_V:
                ADC: ADC2_IN14
                sensor: five_volt_voltage_reading
            Overcurrent_Event:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_0_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_1_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_2_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_3_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_4_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_5_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_6_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_0_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_1_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_2_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_3_Overcurrent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_0_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_1_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_2_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_3_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_4_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_5_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Twelve_Volt_6_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_0_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_1_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_2_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            Five_Volt_3_Overcurrent_Count:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            PLM_Temp_degrees:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            PLM_Humidity_percent:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10
            PLM_Micro_Temp:
                samples_buffered: 10
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 10


            

            



# TODO
# Channel overcurrent events for every channel and num times overcurrented
# Move messages from plm_misc to be listed here
# Temp and humidity
# Micro temp if possible
